services:
  livestream-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livestream-manager
    restart: always
    network_mode: host
    volumes:
      - ./data:/app/data
      - /volume1/Beamer/FreeShow/Media:/app/public/thumbnails
    environment:
      - NODE_ENV=production
      - PORT=3000

  companion:
    image: companion-nas-v3-final:latest
    container_name: companion
    restart: always
    network_mode: host
    volumes:
      - ./companion-data:/companion
