services:
  livestream-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livestream-manager
    restart: always
    ports:
      - "3005:3005"
      - "5004-5007:5004-5007/udp"
    volumes:
      - ./data:/app/data
      - /volume1/Beamer/FreeShow/Media:/app/public/thumbnails
    environment:
      - NODE_ENV=production
      - PORT=3005
    networks:
      - ark-net

  companion:
    image: companion-nas-v4-3-4:latest
    container_name: companion
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./companion-data:/companion
    networks:
      - ark-net

  qlcplus:
    build:
      context: .
      dockerfile: config/qlcplus/Dockerfile
    container_name: qlcplus
    restart: always
    network_mode: host
    volumes:
      - ./config/ark_church_lighting.qxw:/QLC/ark_church_lighting.qxw
      - ./config/qlcplus/config:/root/.config/qlcplus


networks:
  ark-net:
    driver: bridge
